// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_l4HwTMwiiZ3lyxsmfgiota3P_y5L9vY',
    appId: '1:108123157840:web:8306f577dd8223c9c2e855',
    messagingSenderId: '108123157840',
    projectId: 'kede-app',
    authDomain: 'kede-app.firebaseapp.com',
    storageBucket: 'kede-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsSl6jDiSIKp0urqdrsj0KlYYOH7TInE',
    appId: '1:108123157840:android:b87850b23e97fafcc2e855',
    messagingSenderId: '108123157840',
    projectId: 'kede-app',
    storageBucket: 'kede-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwtKht6uzN4gdL2o3G_f0tqjMuIuFM3mM',
    appId: '1:108123157840:ios:610a630c8269f417c2e855',
    messagingSenderId: '108123157840',
    projectId: 'kede-app',
    storageBucket: 'kede-app.firebasestorage.app',
    iosBundleId: 'com.example.kede',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwtKht6uzN4gdL2o3G_f0tqjMuIuFM3mM',
    appId: '1:108123157840:ios:610a630c8269f417c2e855',
    messagingSenderId: '108123157840',
    projectId: 'kede-app',
    storageBucket: 'kede-app.firebasestorage.app',
    iosBundleId: 'com.example.kede',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_l4HwTMwiiZ3lyxsmfgiota3P_y5L9vY',
    appId: '1:108123157840:web:9535d2d67a09f2edc2e855',
    messagingSenderId: '108123157840',
    projectId: 'kede-app',
    authDomain: 'kede-app.firebaseapp.com',
    storageBucket: 'kede-app.firebasestorage.app',
  );
}
